// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcynetlchrrsoyflpkxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjeW5ldGxjaHJyc295Zmxwa3hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MjA1NTQsImV4cCI6MjA2NzM5NjU1NH0.7xuGu5t0X128TkwbhaM9ttZvaf_YjcfFZQYFapBfiVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});